addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.0.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.0.0")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"             % "2.3.0")
addSbtPlugin("com.github.sbt"     % "sbt-jacoco"               % "3.1.0-M3")
addSbtPlugin("com.eed3si9n"       % "sbt-assembly"             % "0.15.0")
