name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: cache cvc4
      id: cache-cvc4
      uses: actions/cache@v1
      with:
        path: external/bin-cvc4
        key: ${{ runner.os }}-build-${{ hashFiles('external/cvc4.sh') }}-3
    - name: cvc4
      if: steps.cache-cvc4.outputs.cache-hit != 'true'
      working-directory: external
      run: ./cvc4.sh

    - name: cache z3
      id: cache-z3
      uses: actions/cache@v1
      with:
        path: external/bin-z3
        key: ${{ runner.os }}-build-${{ hashFiles('external/z3.sh') }}-3
    - name: z3
      if: steps.cache-z3.outputs.cache-hit != 'true'
      working-directory: external
      run: ./z3.sh

    - name: Move Binaries to Common Dir
      run: |
       mkdir -p external/bin
       cp external/bin-cvc4/*  external/bin/
       cp external/bin-z3/*    external/bin/
       ls external/bin/

    - name: Make Binaries Executable
      run: chmod +x $GITHUB_WORKSPACE/external/bin/*

    - name: Add Binaries To Path
      run: |
       ls $GITHUB_WORKSPACE/external/bin/
       echo "$GITHUB_WORKSPACE/external/bin/" >> $GITHUB_PATH
    - name: Print Dependency Versions and Paths
      run: |
       echo "CVC4"
       cvc4 --version
       which cvc4
       echo ""
       echo "Z3"
       z3 --version
       which z3

    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
        
    - name: Cache SBT ivy cache
      uses: actions/cache@v1
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}

    - name: Cache SBT
      uses: actions/cache@v1
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

    - name: Coverage
      run: sbt jacoco